### ISSUE TITLE
Is there any example?

### ISSUE THREAD

**Issue by ykk648** [florianvazelle/deep-fake#2]
hello, is there any face-swap examples to show?

**Comment by florianvazelle** [comment]
Hi, of course 😃

I recorded some videos for you :
- [simple delaunay](https://me.phlowrient.ovh/resources/video/deep_fake/demo-delaunay-deep-fake.mp4)
- [with affine transformation](https://florianvazelle.github.io/resources/video/deep_fake/demo-affine-deep-fake.mp4) 
- [with seamless cloning](https://florianvazelle.github.io/resources/video/deep_fake/demo-seamless-deep-fake.mp4)

To reproduce it, you can simply run :
```
./build/bin/deep_fake.exe --in assets/images/3.jpg
```

The performance is better with a webcam, rather than a video.  
For this, you can replace [`m_camera("./assets/toto.mp4")`](https://github.com/florianvazelle/deep-fake/blob/main/src/FaceDetector.cpp#L5) by `m_camera(0)`.

**Comment by ykk648** [comment]
thanks a lot, appreciate your work.
